# .github/workflows/data-collection.yml
name: 공공데이터 수집

on:
  workflow_dispatch:
    inputs:
      data_type:
        description: '실거래(real-estate) vs 미분양(notsold) vs 인구(population)'
        required: true
        type: choice
        default: 'real-estate'
        options:
          - real-estate
          - notsold
          - population
      region_name:
        description: '시군구 (예: 경상남도 진주시 또는 서울 종로구)'
        required: true
        default: '경상남도 진주시'
      # 실거래 전용
      start_year:
        description: '실거래 시작 연도 (YYYY)'
        required: false
        default: '2020'
      # 미분양·인구 공통
      start:
        description: '미분양/인구 시작 기간 (YYYYMM)'
        required: false
        default: '202501'
      end:
        description: '미분양/인구 종료 기간 (YYYYMM)'
        required: false
        default: '202505'
      output:
        description: '출력 파일명'
        required: false
        default: 'report.xlsx'

jobs:
  collect:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}
      PUBLIC_DATA_API_KEY: ${{ secrets.PUBLIC_DATA_API_KEY }}
      MOLIT_STATS_KEY:     ${{ secrets.MOLIT_STATS_KEY }}
      SERVICE_POP_KEY:     ${{ secrets.SERVICE_POP_KEY }}

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 데이터 수집 실행
        run: |
          case "${{ github.event.inputs.data_type }}" in
            real-estate)
              python real_estate_report.py \
                --region-name "${{ github.event.inputs.region_name }}" \
                --start-year "${{ github.event.inputs.start_year }}" \
                --output "${{ github.event.inputs.output }}"
              ;;
            notsold)
              python notsold.py \
                --region-name "${{ github.event.inputs.region_name }}" \
                --start "${{ github.event.inputs.start }}" \
                --end "${{ github.event.inputs.end }}" \
                --output "${{ github.event.inputs.output }}"
              ;;
            population)
              python population_report.py \
                --region-name "${{ github.event.inputs.region_name }}" \
                --start "${{ github.event.inputs.start }}" \
                --end "${{ github.event.inputs.end }}" \
                --output "${{ github.event.inputs.output }}"
              ;;
            *)
              echo "지원하지 않는 data_type: ${{ github.event.inputs.data_type }}"
              exit 1
              ;;
          esac

      - name: 결과 업로드
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ${{ github.event.inputs.output }}
