# .github/workflows/data-collection.yml
name: 공공데이터 수집

on:
  workflow_dispatch:
    inputs:
      data_type:
        description: 'All-in-one(All-in-one) vs 실거래(실거래(매매,전월세,분양권) 데이터) vs 미분양(미분양 현황) vs 인구(인구 현황)'
        required: true
        type: choice
        default: 'all'
        options:
          - all
          - real-estate
          - notsold
          - population
      region_name:
        description: '시도[ 시군구[ 읍면동]] (예: 경상남도 진주시)'
        required: true
        default: '경상남도 진주시'
      # 실거래 전용
      start_year:
        description: '실거래 시작 연도 (YYYY)'
        required: false
        default: '2020'
      # 미분양·인구 공통
      start:
        description: '미분양/인구 시작 기간 (YYYYMM)'
        required: false
        default: '202501'
      end:
        description: '미분양/인구 종료 기간 (YYYYMM)'
        required: false
        default: '202505'
      output:
        description: '출력 파일명 (All-in-one 선택 시 무시됩니다)'
        required: false
        default: 'report.xlsx'

jobs:
  collect:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}
      PUBLIC_DATA_API_KEY: ${{ secrets.PUBLIC_DATA_API_KEY }}
      MOLIT_STATS_KEY:     ${{ secrets.MOLIT_STATS_KEY }}
      POP_KEY:             ${{ secrets.POP_KEY }}

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 데이터 수집 실행
        run: |
          REGION="${{ github.event.inputs.region_name }}"
          case "${{ github.event.inputs.data_type }}" in

            all)
              # 1) 실거래
              REAL_OUT="국토교통부 실거래데이터_${REGION}.xlsx"
              python real_estate_report.py \
                --region-name "${REGION}" \
                --start-year "${{ github.event.inputs.start_year }}" \
                --output "${REAL_OUT}"
              # 2) 미분양
              NOTSOLD_OUT="미분양 현황_${REGION}.xlsx"
              python notsold.py \
                --region-name "${REGION}" \
                --start "${{ github.event.inputs.start }}" \
                --end   "${{ github.event.inputs.end }}" \
                --output "${NOTSOLD_OUT}"
              # 3) 인구·세대
              POP_OUT="인구 현황_${REGION}.xlsx"
              python population_report.py \
                --region-name "${REGION}" \
                --start "${{ github.event.inputs.start }}" \
                --end   "${{ github.event.inputs.end }}" \
                --output "${POP_OUT}"
              ;;

            real-estate)
              OUT="국토교통부 실거래데이터_${REGION}.xlsx"
              python real_estate_report.py \
                --region-name "${REGION}" \
                --start-year "${{ github.event.inputs.start_year }}" \
                --output "${OUT}"
              ;;

            notsold)
              OUT="미분양 현황_${REGION}.xlsx"
              python notsold.py \
                --region-name "${REGION}" \
                --start "${{ github.event.inputs.start }}" \
                --end   "${{ github.event.inputs.end }}" \
                --output "${OUT}"
              ;;

            population)
              OUT="인구 현황_${REGION}.xlsx"
              python population_report.py \
                --region-name "${REGION}" \
                --start "${{ github.event.inputs.start }}" \
                --end   "${{ github.event.inputs.end }}" \
                --output "${OUT}"
              ;;

            *)
              echo "지원하지 않는 data_type: ${{ github.event.inputs.data_type }}"
              exit 1
              ;;
          esac

      - name: 결과 업로드
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: '*.xlsx'
