name: 공공데이터 수집

on:
  workflow_dispatch:
    inputs:
      data_type:
        description: >
          요청 데이터  
          • all: All-in-one (실거래 + 미분양 + 인구)  
          • real-estate: 실거래(매매,전월세,분양권)  
          • notsold: 미분양 현황  
          • population: 인구 현황  
        required: true
        type: choice
        default: 'all'
        options:
          - all
          - real-estate
          - notsold
          - population
      region_name:
        description: '시도[ 시군구[ 읍면동]] (예: 경상남도 진주시)'
        required: true
        default: '경상남도 진주시'
      start:
        description: '조회 시작 시점 (YYYYMM)'
        required: false
        default: '202001'
      end:
        description: '조회 종료 시점 (YYYYMM)'
        required: false
        default: '${{ github.event.inputs.start }}'
      min_area_sqm:
        description: '(선택) 실거래 조회 최소 전용면적 (㎡)'
        required: false
        default: ''
      max_area_sqm:
        description: '(선택) 실거래 조회 최대 전용면적 (㎡)'
        required: false
        default: ''

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      PUBLIC_DATA_API_KEY: ${{ secrets.PUBLIC_DATA_API_KEY }}
      MOLIT_STATS_KEY:     ${{ secrets.MOLIT_STATS_KEY }}
      POP_KEY:             ${{ secrets.POP_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 데이터 수집 실행
        run: |
          TYPE="${{ github.event.inputs.data_type }}"
          REGION="${{ github.event.inputs.region_name }}"
          START="${{ github.event.inputs.start }}"
          END="${{ github.event.inputs.end }}"
          MIN_AREA="${{ github.event.inputs.min_area_sqm }}"
          MAX_AREA="${{ github.event.inputs.max_area_sqm }}"

          case "${TYPE}" in
            all)
              OUT1="국토교통부 실거래데이터_${REGION}.xlsx"
              python real_estate_report.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                ${MIN_AREA:+--min-area "${MIN_AREA}"} \
                ${MAX_AREA:+--max-area "${MAX_AREA}"} \
                --output "${OUT1}"
              # ... notsold.py, population_report.py 는 그대로 start/end 사용 ...
              ;;
            real-estate)
              OUT="국토교통부 실거래데이터_${REGION}.xlsx"
              python real_estate_report.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                ${MIN_AREA:+--min-area "${MIN_AREA}"} \
                ${MAX_AREA:+--max-area "${MAX_AREA}"} \
                --output "${OUT}"
              ;;
            notsold)
              # ...
              ;;
            population)
              # ...
              ;;
          esac

      - uses: actions/upload-artifact@v4
        with: { name: reports, path: '*.xlsx' }
