name: 공공데이터 수집

on:
  workflow_dispatch:
    inputs:
      data_type:
        description: >
          요청 데이터  
          • all: All-in-one (실거래 + 미분양 + 인구 + 월별 매매가격지수)  
          • real-estate: 실거래(매매,전월세,분양권)  
          • notsold: 미분양 현황  
          • population: 인구 현황  
          • monthly-price-index: 월별 매매가격지수  
        required: true
        type: choice
        default: all
        options:
          - all
          - real-estate
          - notsold
          - population
          - monthly-price-index
      region_name:
        description: '시도[ 시군구[ 읍면동]] (예: 경상남도 진주시)'
        required: true
        default: '경상남도 진주시'
      start:
        description: '조회 시작 시점 (YYYYMM)'
        required: true
        default: '202001'
      end:
        description: '조회 종료 시점 (YYYYMM)'
        required: true
        default: '202512'
      min_area:
        description: '(선택) 실거래 조회 최소 면적 (㎡ 기준)'
        required: false
        default: ''
      max_area:
        description: '(선택) 실거래 조회 최대 면적 (㎡ 기준)'
        required: false
        default: ''

jobs:
  collect:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}
      PUBLIC_DATA_API_KEY: ${{ secrets.PUBLIC_DATA_API_KEY }}
      MOLIT_STATS_KEY:     ${{ secrets.MOLIT_STATS_KEY }}
      POP_KEY:             ${{ secrets.POP_KEY }}
      REB_API_KEY:         ${{ secrets.REB_API_KEY }}

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 데이터 수집 실행
        run: |
          TYPE="${{ github.event.inputs.data_type }}"
          REGION="${{ github.event.inputs.region_name }}"
          START="${{ github.event.inputs.start }}"
          END="${{ github.event.inputs.end }}"
          MIN_AREA="${{ github.event.inputs.min_area }}"
          MAX_AREA="${{ github.event.inputs.max_area }}"

          case "${TYPE}" in
            all)
              # 1) 실거래
              OUT1="국토교통부 실거래데이터_${REGION}.xlsx"
              python real_estate_report.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                ${MIN_AREA:+--min-area "${MIN_AREA}"} \
                ${MAX_AREA:+--max-area "${MAX_AREA}"} \
                --output "${OUT1}"

              # 2) 미분양
              OUT2="미분양 현황_${REGION}.xlsx"
              python notsold.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                --output "${OUT2}"

              # 3) 인구
              OUT3="인구 현황_${REGION}.xlsx"
              python population_report.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                --output "${OUT3}"

              # 4) 월별 매매가격지수
              OUT4="월별매매가격지수_${REGION}.xlsx"
              python monthly_price_index.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                --output "${OUT4}"
              ;;

            real-estate)
              OUT="국토교통부 실거래데이터_${REGION}.xlsx"
              python real_estate_report.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                ${MIN_AREA:+--min-area "${MIN_AREA}"} \
                ${MAX_AREA:+--max-area "${MAX_AREA}"} \
                --output "${OUT}"
              ;;

            notsold)
              OUT="미분양 현황_${REGION}.xlsx"
              python notsold.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                --output "${OUT}"
              ;;

            population)
              OUT="인구 현황_${REGION}.xlsx"
              python population_report.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                --output "${OUT}"
              ;;

            monthly-price-index)
              OUT="월별매매가격지수_${REGION}.xlsx"
              python monthly_price_index.py \
                --region-name "${REGION}" \
                --start "${START}" \
                --end   "${END}" \
                --output "${OUT}"
              ;;

            *)
              echo "지원하지 않는 data_type: ${TYPE}"
              exit 1
              ;;
          esac

      - name: 결과 업로드
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: '*.xlsx'
