name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Run module smoke tests
        env:
          MOLIT_STATS_KEY: ${{ secrets.MOLIT_STATS_KEY }}
        run: |
          # 간단히 각 명령어가 에러 없이 실행되는지 확인
          python main.py real-estate \
            --region-name "서울 종로구" --start "202501" --end "202505" --output smoke_real_estate.xlsx
          python main.py population \
            --start "202501" --end "202505" --output smoke_population.xlsx
          python main.py notsold \
            --region-name "서울 종로구" --start "202501" --end "202505" --output smoke_notsold.xlsx

      - name: Upload smoke-test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: smoke-outputs
          path: |
            smoke_real_estate.xlsx
            smoke_population.xlsx
            smoke_notsold.xlsx
