name: 공공데이터 실거래 리포트

on:
  workflow_dispatch: {}      # 수동 실행을 위해 반드시 빈 객체로 명시
  schedule:
    - cron: '0 0 * * *'      # 매일 UTC 00:00 (KST 09:00)에 자동 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 리포트 실행
        env:
          PUBLIC_DATA_API_KEY: ${{ secrets.PUBLIC_DATA_API_KEY }}
        run: |
          python real_estate_report.py \
            --region-name "충청남도 천안시 동남구" \
            --start-year 2020 \
            --built-after 2015 \
            --output cheonan_report.xlsx

      - name: 결과 업로드
        uses: actions/upload-artifact@v4
        with:
          name: cheonan_report
          path: cheonan_report.xlsx
